# Generated by Django 4.2.7 on 2024-05-27 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt_title', models.TextField(blank=True)),
                ('text', models.TextField(blank=True)),
                ('next', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.prompt')),
            ],
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.prompt')),
            ],
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.branch')),
                ('next', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.block')),
            ],
        ),
    ]
